name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: test (ruby ${{ matrix.ruby }} / rails ${{ matrix.rails_version }} / blacklight ${{ matrix.blacklight_version }} ${{ matrix.additional_name }})
    strategy:
      matrix:
        ruby: [2.7, '3.0']
        rails_version: ['6.1.7', '7.0.4']
        blacklight_version: ['~> 7.0']
        experimental: [false]
        additional_engine_cart_rails_options: ['']
        additional_name: ['']
        include:
        - ruby: '3.1'
          rails_version: '7.0.4'
          blacklight_version: '~> 7.0'
          experimental: false
        - ruby: '3.2'
          rails_version: '7.0.4'
          blacklight_version: '~> 8.0'
          experimental: false
        - ruby: '3.2'
          rails_version: '7.0.4'
          blacklight_version: 'github'
          experimental: true
        - ruby: '3.2'
          rails_version: '7.0.4'
          blacklight_version: 'github'
          experimental: true
          additional_engine_cart_rails_options: -a propshaft
          additional_name: '/ Propshaft'
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      BLACKLIGHT_VERSION: ${{ matrix.blacklight_version }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies with Rails ${{ matrix.rails_version }}
      run: bundle install
    - name: Run tests
      run: bundle exec rake
