name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: test (ruby ${{ matrix.ruby }} / rails ${{ matrix.rails_version }} / blacklight ${{ matrix.blacklight_version }} ${{ matrix.additional_name }})
    strategy:
      matrix:
        ruby: ["3.2", "3.3"]
        rails_version: ["7.2.2"]
        blacklight_version: ["~> 7.0"]
        experimental: [false]
        additional_engine_cart_rails_options: [""]
        additional_name: [""]
        view_component_version: ["~> 3.12"]
        include:
          - ruby: "3.2"
            rails_version: "7.0.4"
            blacklight_version: "~> 8.0"
            experimental: false
            additional_name: Blacklight 8
          - ruby: "3.2"
            rails_version: "7.0.4"
            blacklight_version: "github"
            experimental: true
            additional_name: Blacklight main branch
          - ruby: "3.2"
            rails_version: "7.0.4"
            blacklight_version: "~> 7.0"
            experimental: false
            view_component_version: "~> 2.83"
            additional_name: "/ ViewComponent 2"
          - ruby: "3.3"
            rails_version: "8.0.0"
            blacklight_version: "~> 8.0"
            experimental: false
            additional_engine_cart_rails_options: --css bootstrap
            additional_name: "/ Blackight 8 / Rails 8"
          - ruby: "3.3"
            rails_version: "7.2.2"
            blacklight_version: "github"
            experimental: true
            additional_engine_cart_rails_options: -a propshaft --css bootstrap
            additional_name: "/ Blacklight main branch with Propshaft"
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
      BLACKLIGHT_VERSION: ${{ matrix.blacklight_version }}
      VIEW_COMPONENT_VERSION: ${{ matrix.view_component_version }}
      ENGINE_CART_RAILS_OPTIONS: "--skip-git --skip-listen --skip-spring --skip-keeps --skip-action-cable --skip-coffee --skip-test ${{ matrix.additional_engine_cart_rails_options }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies with Rails ${{ matrix.rails_version }}
        run: bundle install
      - name: Run tests
        run: bundle exec rake
